services:
  test-db:
    image: postgres:15-alpine
    container_name: sistema-ocorrencias-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin_password_test
      POSTGRES_DB: sistema_ocorrencias_test
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data:
